// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: srpc.proto

#include "srpc.pb.h"
#include "srpc.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace srpc {

static const char* rpc_method_names[] = {
  "/srpc.rpc/call",
};

std::unique_ptr< rpc::Stub> rpc::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< rpc::Stub> stub(new rpc::Stub(channel, options));
  return stub;
}

rpc::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_call_(rpc_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status rpc::Stub::call(::grpc::ClientContext* context, const ::srpc::req& request, ::srpc::res* response) {
  return ::grpc::internal::BlockingUnaryCall< ::srpc::req, ::srpc::res, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_call_, context, request, response);
}

void rpc::Stub::async::call(::grpc::ClientContext* context, const ::srpc::req* request, ::srpc::res* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::srpc::req, ::srpc::res, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_call_, context, request, response, std::move(f));
}

void rpc::Stub::async::call(::grpc::ClientContext* context, const ::srpc::req* request, ::srpc::res* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_call_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::srpc::res>* rpc::Stub::PrepareAsynccallRaw(::grpc::ClientContext* context, const ::srpc::req& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::srpc::res, ::srpc::req, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_call_, context, request);
}

::grpc::ClientAsyncResponseReader< ::srpc::res>* rpc::Stub::AsynccallRaw(::grpc::ClientContext* context, const ::srpc::req& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynccallRaw(context, request, cq);
  result->StartCall();
  return result;
}

rpc::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      rpc_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< rpc::Service, ::srpc::req, ::srpc::res, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](rpc::Service* service,
             ::grpc::ServerContext* ctx,
             const ::srpc::req* req,
             ::srpc::res* resp) {
               return service->call(ctx, req, resp);
             }, this)));
}

rpc::Service::~Service() {
}

::grpc::Status rpc::Service::call(::grpc::ServerContext* context, const ::srpc::req* request, ::srpc::res* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace srpc

